version: "1.0"

stages:
  - "init"
  - "clone"
  - "build"
  - "push"
  - "release"

steps:
  decide_release:
    title: Decide Release
    stage: init
    image: codefresh/cli
    shell: bash
    when:
      condition:
        all:
          mainBranch: '"${{CF_BRANCH}}" == "main"'
          noCiCdMessage: 'includes("${{CF_COMMIT_MESSAGE}}", "Version Release") == false'
    commands:
      - cf_export IS_RELEASE=true

  init:
    title: Init
    stage: init
    image: codefresh/cli
    shell: bash
    commands:
      - cf_export GITHUB_TOKEN=$(codefresh get context github --decrypt -o yaml | yq -y .spec.data.auth.password)
      - cf_export MAIN_REPO_PATH=/codefresh/volume/repo.git
      - export PRODUCT_NAME=${{CF_REPO_NAME}}
      - cf_export PRODUCT_NAME=${PRODUCT_NAME}
      - export CICD_REPO_NAME=cicd
      - cf_export CICD_REPO_NAME=${CICD_REPO_NAME}
      - cf_export CICD_REPO_PATH=/codefresh/volume/${CICD_REPO_NAME}.git
      - export IMAGE_NAME=kubevious/${PRODUCT_NAME}
      - cf_export IMAGE_NAME=${IMAGE_NAME}
      - 'echo "Is Release: ${IS_RELEASE}"'
      - 'echo "Product: ${PRODUCT_NAME}"'
      - 'echo "Repo: ${{CF_REPO_NAME}}"'
      - 'echo "Branch: ${{CF_BRANCH}}"'
      - 'echo "Revision: ${{CF_REVISION}}"'
      - 'echo "Author: ${{CF_COMMIT_AUTHOR}}"'
      - 'echo "Message: ${{CF_COMMIT_MESSAGE}}"'
      - 'echo "Image Name: ${IMAGE_NAME}"'

  clone:
    title: Clone Repo
    stage: clone
    image: "alpine/git:latest"
    working_directory: "/codefresh/volume"
    commands:
      - pwd
      - ls -la
      - rm -rf ${{MAIN_REPO_PATH}}
      - "git clone https://${{CF_REPO_OWNER}}:${{GITHUB_TOKEN}}@github.com/${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}.git ${{MAIN_REPO_PATH}}"
      - ls -la
      - cd ${{MAIN_REPO_PATH}}
      - git reset --hard ${{CF_REVISION}}
      - ls -la

  clone_cicd:
    title: Clone CI/CD Repo
    stage: clone
    image: "alpine/git:latest"
    working_directory: "/codefresh/volume"
    when:
      condition:
        all:
          isRelease: '"${{IS_RELEASE}}" == "true"'
    commands:
      - pwd
      - ls -la
      - rm -rf ${{CICD_REPO_PATH}}
      - "git clone https://${{CF_REPO_OWNER}}:${{GITHUB_TOKEN}}@github.com/${{CF_REPO_OWNER}}/${{CICD_REPO_NAME}}.git ${{CICD_REPO_PATH}}"
      - ls -la
      - cd ${{CICD_REPO_PATH}}
      - ls -la

  inject_version:
    title: Inject Version
    stage: build
    image: codefresh/cli
    shell: bash
    working_directory: "${{MAIN_REPO_PATH}}"
    when:
      condition:
        all:
          isRelease: '"${{IS_RELEASE}}" == "true"'
    commands:
      - pwd
      - ls -la
      - source ${{CICD_REPO_PATH}}/process-version-bump.sh
      - echo "NEW VERSION=${PRODUCT_VERSION}"
      - source version.sh
      - cf_export PRODUCT_VERSION=${PRODUCT_VERSION}
      - cf_export DOCKER_TAG=${PRODUCT_VERSION}
      - git status
      - git --no-pager diff

  prepare:
    title: Prepare Dependencies
    stage: build
    image: "kubevious/node-builder:14"
    working_directory: "${{MAIN_REPO_PATH}}"
    commands:
      - yarn install --frozen-lockfile

  compile:
    title: Compile
    stage: build
    image: "kubevious/node-builder:14"
    working_directory: "${{MAIN_REPO_PATH}}"
    commands:
      - npm run build

  docker_build:
    title: Building OSS Image
    stage: build
    type: build
    image_name: "${{IMAGE_NAME}}"
    working_directory: "${{MAIN_REPO_PATH}}"
    disable_push: true

  push_dockerhub:
    title: Pushing OSS Image to DockerHub
    stage: push
    type: push
    image_name: "${{IMAGE_NAME}}"
    registry: "dockerhub"
    candidate: "${{docker_build}}"
    tags:
      - "${{DOCKER_TAG}}"
    when:
      condition:
        all:
          isRelease: '"${{IS_RELEASE}}" == "true"'

  commit_main_repo:
    title: Commit Version Changes
    stage: release
    image: codefresh/cli
    working_directory: "${{MAIN_REPO_PATH}}"
    when:
      condition:
        all:
          isRelease: '"${{IS_RELEASE}}" == "true"'
    commands:
      - ${{CICD_REPO_PATH}}/cicd-commit-product-repo.sh
