---
apiVersion: kubevious.io/v1alpha1
kind: WorkloadProfile
metadata:
  name: primary-az
spec:
  nodeSelector:
    my.availability.zone: east-1-a
  
---
apiVersion: kubevious.io/v1alpha1
kind: WorkloadProfile
metadata:
  name: secondary-az
spec:
  nodeSelector:
    my.availability.zone: east-1-b
  # affinity: ...

---
apiVersion: kubevious.io/v1alpha1
kind: WorkloadProfile
metadata:
  name: reserved-node
spec:
  nodeSelector:
    node-kind: RESERVED

---
apiVersion: kubevious.io/v1alpha1
kind: WorkloadProfile
metadata:
  name: spot-node
spec:
  nodeSelector:
    node-kind: SPOT

---
apiVersion: kubevious.io/v1alpha1
kind: WorkloadProfile
metadata:
  name: lambda
spec:
  infra: serverless