---
apiVersion: kubevious.io/v1alpha1
kind: WorkloadProfile
metadata:
  name: primary-az
spec:
  nodeSelector:
    failure-domain.beta.kubernetes.io/zone: us-east-1a
  
---
apiVersion: kubevious.io/v1alpha1
kind: WorkloadProfile
metadata:
  name: secondary-az
spec:
  nodeSelector:
    failure-domain.beta.kubernetes.io/zone: us-east-1b

---
apiVersion: kubevious.io/v1alpha1
kind: WorkloadProfile
metadata:
  name: reserved-node
spec:
  nodeSelector:
    eks.amazonaws.com/capacityType: ON_DEMAND

---
apiVersion: kubevious.io/v1alpha1
kind: WorkloadProfile
metadata:
  name: spot-node
spec:
  nodeSelector:
    eks.amazonaws.com/capacityType: SPOT

---
apiVersion: kubevious.io/v1alpha1
kind: WorkloadProfile
metadata:
  name: fargate
spec:
  labels:
    fargate: 'yes'
  annotations:
    run-in-fargate: 'yes'
