apiVersion: kubevious.io/v1alpha1
kind: Workload
metadata:
  name: nginx-simple
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-simple
  template:
    metadata:
      labels:
        app: nginx-simple
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
  schedule:
  - name: reserved
    replicas: 50%
    nodeSelector:
      nodetype: ON_DEMAND
  - name: spot
    nodeSelector:
      nodetype: SPOT
  - name: fargate
    nodeSelector:
      nodetype: SPOT